name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Diupdate dari v3 ke v4
    - name: Set up Python
      uses: actions/setup-python@v5 # Diupdate dari v4 ke v5
      with:
        python-version: "3.10"
    - name: Run Tests
      run: |
        python -m unittest discover tests